language: python

python:
 - "3.5"
 - "3.6"

install:
 - gzip -d net/keras_net_v0_2017aug7.h5
 - pip install -I Cython==0.23
 - pip install -r requirements.txt
 - pip install -r test_requirements.txt

script:
 - pytest